CREATE TABLE "memory_logs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "memory_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"timestamp" timestamp DEFAULT now() NOT NULL,
	"run_id" varchar(36) NOT NULL,
	"label" varchar(100) NOT NULL,
	"heap_used_mb" real NOT NULL,
	"heap_total_mb" real NOT NULL,
	"rss_mb" real NOT NULL,
	"external_mb" real NOT NULL,
	"metadata" json
);
--> statement-breakpoint
CREATE TABLE "season_snapshots" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "season_snapshots_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"season_id" integer NOT NULL,
	"queue_type" text NOT NULL,
	"queue_id" text NOT NULL,
	"minio_key" text,
	"uploaded_by" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "seasons" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "seasons_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"start_date" timestamp NOT NULL,
	"end_date" timestamp,
	"is_active" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "player_games" ALTER COLUMN "queue_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "player_games" ADD COLUMN "deck" text;--> statement-breakpoint
ALTER TABLE "player_games" ADD COLUMN "stake" text;--> statement-breakpoint
ALTER TABLE "player_games" ADD COLUMN "season" text;--> statement-breakpoint
ALTER TABLE "season_snapshots" ADD CONSTRAINT "season_snapshots_season_id_seasons_id_fk" FOREIGN KEY ("season_id") REFERENCES "public"."seasons"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "season_snapshots_season_id_idx" ON "season_snapshots" USING btree ("season_id");--> statement-breakpoint
CREATE UNIQUE INDEX "season_snapshots_season_queue_unique" ON "season_snapshots" USING btree ("season_id","queue_type");--> statement-breakpoint
CREATE INDEX "season_idx" ON "player_games" USING btree ("season");