CREATE TABLE "games" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "games_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"log_file_id" integer NOT NULL,
	"game_index" integer NOT NULL,
	"host" text,
	"guest" text,
	"log_owner_name" text,
	"opponent_name" text,
	"is_host" boolean,
	"host_connection_id" text,
	"guest_connection_id" text,
	"host_encrypt_id" text,
	"guest_encrypt_id" text,
	"deck" text,
	"seed" text,
	"stake" integer,
	"ruleset" text,
	"options" json,
	"winner" text,
	"start_date" timestamp NOT NULL,
	"end_date" timestamp,
	"duration_seconds" integer,
	"money_gained" integer,
	"money_spent" integer,
	"opponent_money_spent" integer,
	"rerolls" integer,
	"reroll_cost_total" integer,
	"opponent_rerolls" integer,
	"opponent_reroll_cost_total" integer,
	"log_owner_final_jokers" json NOT NULL,
	"opponent_final_jokers" json NOT NULL,
	"log_owner_vouchers" json NOT NULL,
	"opponent_vouchers" json NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "games" ADD CONSTRAINT "games_log_file_id_log_files_id_fk" FOREIGN KEY ("log_file_id") REFERENCES "public"."log_files"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "games_log_file_id_idx" ON "games" USING btree ("log_file_id");--> statement-breakpoint
CREATE INDEX "games_host_idx" ON "games" USING btree ("host");--> statement-breakpoint
CREATE INDEX "games_guest_idx" ON "games" USING btree ("guest");--> statement-breakpoint
CREATE INDEX "games_host_connection_id_idx" ON "games" USING btree ("host_connection_id");--> statement-breakpoint
CREATE INDEX "games_guest_connection_id_idx" ON "games" USING btree ("guest_connection_id");--> statement-breakpoint
CREATE INDEX "games_host_encrypt_id_idx" ON "games" USING btree ("host_encrypt_id");--> statement-breakpoint
CREATE INDEX "games_guest_encrypt_id_idx" ON "games" USING btree ("guest_encrypt_id");--> statement-breakpoint
CREATE INDEX "games_deck_idx" ON "games" USING btree ("deck");--> statement-breakpoint
CREATE INDEX "games_seed_idx" ON "games" USING btree ("seed");--> statement-breakpoint
CREATE INDEX "games_stake_idx" ON "games" USING btree ("stake");--> statement-breakpoint
CREATE INDEX "games_ruleset_idx" ON "games" USING btree ("ruleset");--> statement-breakpoint
CREATE INDEX "games_winner_idx" ON "games" USING btree ("winner");--> statement-breakpoint
CREATE INDEX "games_start_date_idx" ON "games" USING btree ("start_date");--> statement-breakpoint
CREATE UNIQUE INDEX "games_log_file_id_game_index_unique" ON "games" USING btree ("log_file_id","game_index");