CREATE TABLE "banned_user_aliases" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "banned_user_aliases_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"banned_user_id" integer NOT NULL,
	"alias" text NOT NULL,
	"alias_lower" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "banned_user_ids" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "banned_user_ids_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"banned_user_id" integer NOT NULL,
	"value" text NOT NULL,
	"value_lower" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "banned_users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "banned_users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"label" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "banned_user_aliases" ADD CONSTRAINT "banned_user_aliases_banned_user_id_banned_users_id_fk" FOREIGN KEY ("banned_user_id") REFERENCES "public"."banned_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "banned_user_ids" ADD CONSTRAINT "banned_user_ids_banned_user_id_banned_users_id_fk" FOREIGN KEY ("banned_user_id") REFERENCES "public"."banned_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "banned_user_aliases_alias_lower_idx" ON "banned_user_aliases" USING btree ("alias_lower");--> statement-breakpoint
CREATE UNIQUE INDEX "banned_user_aliases_user_alias_unique" ON "banned_user_aliases" USING btree ("banned_user_id","alias_lower");--> statement-breakpoint
CREATE INDEX "banned_user_ids_value_lower_idx" ON "banned_user_ids" USING btree ("value_lower");--> statement-breakpoint
CREATE UNIQUE INDEX "banned_user_ids_user_value_unique" ON "banned_user_ids" USING btree ("banned_user_id","value_lower");