CREATE TABLE "poll_ballot_rankings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "poll_ballot_rankings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ballot_id" integer NOT NULL,
	"option_id" integer NOT NULL,
	"rank" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "poll_ballots" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "poll_ballots_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"poll_id" integer NOT NULL,
	"user_id" varchar(255) NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "poll_options" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "poll_options_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"poll_id" integer NOT NULL,
	"label" text NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "polls" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "polls_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"uuid" varchar(255) NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"status" varchar(255) DEFAULT 'open' NOT NULL,
	"closed_at" timestamp,
	"closes_at" timestamp,
	"created_by" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "poll_ballot_rankings" ADD CONSTRAINT "poll_ballot_rankings_ballot_id_poll_ballots_id_fk" FOREIGN KEY ("ballot_id") REFERENCES "public"."poll_ballots"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "poll_ballot_rankings" ADD CONSTRAINT "poll_ballot_rankings_option_id_poll_options_id_fk" FOREIGN KEY ("option_id") REFERENCES "public"."poll_options"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "poll_ballots" ADD CONSTRAINT "poll_ballots_poll_id_polls_id_fk" FOREIGN KEY ("poll_id") REFERENCES "public"."polls"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "poll_ballots" ADD CONSTRAINT "poll_ballots_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "poll_options" ADD CONSTRAINT "poll_options_poll_id_polls_id_fk" FOREIGN KEY ("poll_id") REFERENCES "public"."polls"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "polls" ADD CONSTRAINT "polls_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "poll_ballot_rankings_ballot_option_idx" ON "poll_ballot_rankings" USING btree ("ballot_id","option_id");--> statement-breakpoint
CREATE UNIQUE INDEX "poll_ballot_rankings_ballot_rank_idx" ON "poll_ballot_rankings" USING btree ("ballot_id","rank");--> statement-breakpoint
CREATE INDEX "poll_ballot_rankings_ballot_idx" ON "poll_ballot_rankings" USING btree ("ballot_id");--> statement-breakpoint
CREATE UNIQUE INDEX "poll_ballots_poll_user_idx" ON "poll_ballots" USING btree ("poll_id","user_id");--> statement-breakpoint
CREATE INDEX "poll_options_poll_id_idx" ON "poll_options" USING btree ("poll_id");--> statement-breakpoint
CREATE UNIQUE INDEX "polls_uuid_idx" ON "polls" USING btree ("uuid");--> statement-breakpoint
UPDATE "user" SET "permissions" = array_append("permissions", 'polls.manage') WHERE 'permissions.manage' = ANY("permissions") AND NOT ('polls.manage' = ANY("permissions"));