CREATE TABLE "mod_policy_categories" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mod_policy_categories_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"name_lower" text NOT NULL,
	"description" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "mod_policy_entries" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mod_policy_entries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"mod_id" text NOT NULL,
	"mod_id_lower" text NOT NULL,
	"status" text NOT NULL,
	"versions" json,
	"name" text NOT NULL,
	"url" text,
	"note" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "mod_policy_entry_categories" (
	"entry_id" integer NOT NULL,
	"category_id" integer NOT NULL,
	CONSTRAINT "mod_policy_entry_categories_entry_id_category_id_pk" PRIMARY KEY("entry_id","category_id")
);
--> statement-breakpoint
ALTER TABLE "mod_policy_entry_categories" ADD CONSTRAINT "mod_policy_entry_categories_entry_id_mod_policy_entries_id_fk" FOREIGN KEY ("entry_id") REFERENCES "public"."mod_policy_entries"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mod_policy_entry_categories" ADD CONSTRAINT "mod_policy_entry_categories_category_id_mod_policy_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."mod_policy_categories"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "mod_policy_categories_name_lower_unique" ON "mod_policy_categories" USING btree ("name_lower");--> statement-breakpoint
CREATE UNIQUE INDEX "mod_policy_entries_mod_id_lower_unique" ON "mod_policy_entries" USING btree ("mod_id_lower");--> statement-breakpoint
CREATE INDEX "mod_policy_entry_categories_category_idx" ON "mod_policy_entry_categories" USING btree ("category_id");