CREATE TABLE "bracket_results" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bracket_results_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"bracket_id" integer NOT NULL,
	"round" integer NOT NULL,
	"slot" integer NOT NULL,
	"score1" integer,
	"score2" integer,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "bracket_seeds" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bracket_seeds_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"bracket_id" integer NOT NULL,
	"position" integer NOT NULL,
	"name" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "brackets" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "brackets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"size" integer DEFAULT 16 NOT NULL,
	"has_third_place" boolean DEFAULT true NOT NULL,
	"is_published" boolean DEFAULT false NOT NULL,
	"created_by" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "bracket_results" ADD CONSTRAINT "bracket_results_bracket_id_brackets_id_fk" FOREIGN KEY ("bracket_id") REFERENCES "public"."brackets"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bracket_seeds" ADD CONSTRAINT "bracket_seeds_bracket_id_brackets_id_fk" FOREIGN KEY ("bracket_id") REFERENCES "public"."brackets"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "brackets" ADD CONSTRAINT "brackets_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "bracket_results_bracket_id_idx" ON "bracket_results" USING btree ("bracket_id");--> statement-breakpoint
CREATE UNIQUE INDEX "bracket_results_bracket_round_slot_idx" ON "bracket_results" USING btree ("bracket_id","round","slot");--> statement-breakpoint
CREATE INDEX "bracket_seeds_bracket_id_idx" ON "bracket_seeds" USING btree ("bracket_id");--> statement-breakpoint
CREATE UNIQUE INDEX "bracket_seeds_bracket_position_idx" ON "bracket_seeds" USING btree ("bracket_id","position");